spring.jpa.hibernate.ddl-auto=update

spring.main.timezone=America/Sao_Paulo

spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

spring.datasource.url=jdbc:postgresql://${POSTGRESHOST}:${POSTGRESPORT}/${POSTGRESDATABASE}
spring.datasource.username=${POSTGRESUSER}
spring.datasource.password=${POSTGRESPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
